/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ArtCanvas { 'base64Data' : string }
export interface DayData {
  'art' : string,
  'day' : bigint,
  'spiritual' : string,
  'gratitude' : string,
  'writing' : string,
}
export interface JournalEntry {
  'artCanvas' : ArtCanvas,
  'writingResponse' : string,
  'spiritualResponse' : string,
  'dayNumber' : bigint,
  'gratitudeAnchor' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeekData {
  'theme' : string,
  'reflectionQuestions' : Array<string>,
  'days' : Array<DayData>,
  'week' : bigint,
  'quote' : string,
  'mandalaHint' : string,
  'intention' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllJournalEntries' : ActorMethod<[], Array<JournalEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getJournalEntry' : ActorMethod<[bigint], [] | [JournalEntry]>,
  'getProgress' : ActorMethod<[], Array<bigint>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWeek' : ActorMethod<[bigint], [] | [WeekData]>,
  'getWeeks' : ActorMethod<[], Array<WeekData>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveJournalEntry' : ActorMethod<
    [bigint, string, string, string, ArtCanvas],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];