/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ArtCanvas = IDL.Record({ 'base64Data' : IDL.Text });
export const JournalEntry = IDL.Record({
  'artCanvas' : ArtCanvas,
  'writingResponse' : IDL.Text,
  'spiritualResponse' : IDL.Text,
  'dayNumber' : IDL.Nat,
  'gratitudeAnchor' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DayData = IDL.Record({
  'art' : IDL.Text,
  'day' : IDL.Nat,
  'spiritual' : IDL.Text,
  'gratitude' : IDL.Text,
  'writing' : IDL.Text,
});
export const WeekData = IDL.Record({
  'theme' : IDL.Text,
  'reflectionQuestions' : IDL.Vec(IDL.Text),
  'days' : IDL.Vec(DayData),
  'week' : IDL.Nat,
  'quote' : IDL.Text,
  'mandalaHint' : IDL.Text,
  'intention' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getJournalEntry' : IDL.Func([IDL.Nat], [IDL.Opt(JournalEntry)], ['query']),
  'getProgress' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWeek' : IDL.Func([IDL.Nat], [IDL.Opt(WeekData)], ['query']),
  'getWeeks' : IDL.Func([], [IDL.Vec(WeekData)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveJournalEntry' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, ArtCanvas],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ArtCanvas = IDL.Record({ 'base64Data' : IDL.Text });
  const JournalEntry = IDL.Record({
    'artCanvas' : ArtCanvas,
    'writingResponse' : IDL.Text,
    'spiritualResponse' : IDL.Text,
    'dayNumber' : IDL.Nat,
    'gratitudeAnchor' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DayData = IDL.Record({
    'art' : IDL.Text,
    'day' : IDL.Nat,
    'spiritual' : IDL.Text,
    'gratitude' : IDL.Text,
    'writing' : IDL.Text,
  });
  const WeekData = IDL.Record({
    'theme' : IDL.Text,
    'reflectionQuestions' : IDL.Vec(IDL.Text),
    'days' : IDL.Vec(DayData),
    'week' : IDL.Nat,
    'quote' : IDL.Text,
    'mandalaHint' : IDL.Text,
    'intention' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getJournalEntry' : IDL.Func([IDL.Nat], [IDL.Opt(JournalEntry)], ['query']),
    'getProgress' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWeek' : IDL.Func([IDL.Nat], [IDL.Opt(WeekData)], ['query']),
    'getWeeks' : IDL.Func([], [IDL.Vec(WeekData)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveJournalEntry' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, ArtCanvas],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };