export interface DayData {
  day: number;
  spiritual: string;
  art: string;
  writing: string;
  gratitude: string;
}

export interface WeekData {
  week: number;
  theme: string;
  intention: string;
  quote: string;
  mandalaHint: string;
  reflectionQuestions: string[];
  days: DayData[];
}

export const WEEKS: WeekData[] = [
  {
    week: 1,
    theme: "Grounding & Awareness",
    intention: "Connect with your body and the present moment.",
    quote: "The foundation of presence is grounding yourself in the now.",
    mandalaHint: "Draw roots, circles, or patterns that anchor your energy.",
    reflectionQuestions: [
      "What felt most stabilizing this week?",
      "Where did you notice resistance?",
      "How did grounding shift your energy?",
    ],
    days: [
      {
        day: 1,
        spiritual: 'What does "being grounded" feel like to you?',
        art: "Draw your feet touching the Earth or roots extending downward.",
        writing: "Describe a moment you felt completely present in your body.",
        gratitude: "Name one thing your body allowed you to experience today.",
      },
      {
        day: 2,
        spiritual: "Where is your energy today — high, low, or scattered?",
        art: "Create a mandala using only 3 colors based on your energy.",
        writing: "Free-write for 5 minutes on what your energy is telling you.",
        gratitude: "Write one thing you appreciate about your current energy.",
      },
      {
        day: 3,
        spiritual: "What anchors you when life feels chaotic?",
        art: 'Create a symbolic "anchor" using shapes, lines, or symbols.',
        writing: "Journal how these anchors show up in daily life.",
        gratitude: "Identify one anchor you relied on today.",
      },
      {
        day: 4,
        spiritual: "What natural elements do you feel connected to?",
        art: "Paint or color earth, air, fire, water around your name.",
        writing: "Write about which element matches your current state.",
        gratitude: "List one way nature nourished you today.",
      },
      {
        day: 5,
        spiritual: "What parts of your body feel strong?",
        art: "Trace your hand and fill it with textures or symbols of strength.",
        writing: "Write a thank-you note to your body.",
        gratitude: "Appreciate one physical capability you often overlook.",
      },
      {
        day: 6,
        spiritual: "How can you return to yourself today?",
        art: "Use earth tones to color a spiral inward.",
        writing: "Describe a ritual that helps you feel safe.",
        gratitude: "Identify one act of self-care you are grateful for.",
      },
      {
        day: 7,
        spiritual: 'What does your "safe space" look and feel like?',
        art: "Draw or color a place where you feel safe and whole.",
        writing: "Journal why this space is meaningful.",
        gratitude: "Acknowledge one comfort within this space.",
      },
    ],
  },
  {
    week: 2,
    theme: "Presence & Observation",
    intention: "Notice the subtle details of your inner and outer world.",
    quote: "Observe without judgment; presence is the art of attention.",
    mandalaHint: "Draw eyes, circles, or patterns representing mindfulness.",
    reflectionQuestions: [
      "What small observations stood out to you?",
      "How did your attention shift through the week?",
      "What surprised you about your daily awareness?",
    ],
    days: [
      {
        day: 8,
        spiritual: "What are you noticing today that you usually overlook?",
        art: 'Create a "mindful eye" using tiny symbols or patterns.',
        writing: "Journal 5 small things you appreciated today.",
        gratitude: "Name one unnoticed blessing.",
      },
      {
        day: 9,
        spiritual: "What emotions are with you today?",
        art: "Use color to abstractly express today's emotions.",
        writing: "Name and describe each emotion without judgment.",
        gratitude: "Appreciate one emotion for the insight it provides.",
      },
      {
        day: 10,
        spiritual: "How do you experience silence?",
        art: "Draw or color sound waves or quiet stillness.",
        writing: "Describe a moment you found beauty in silence.",
        gratitude: "Acknowledge the gift of stillness today.",
      },
      {
        day: 11,
        spiritual: "What does your intuition sound like?",
        art: "Use symbols or shapes that represent inner wisdom.",
        writing: "Write about how intuition has guided you.",
        gratitude: "Note one time your inner voice helped you.",
      },
      {
        day: 12,
        spiritual: "What detail in nature speaks to you?",
        art: "Sketch a natural object you admire (leaf, rock, bird).",
        writing: "Describe what you see and what it teaches you.",
        gratitude: "Recognize one lesson nature gave you today.",
      },
      {
        day: 13,
        spiritual: "What rhythms guide your day?",
        art: "Color a clock or timeline of your day in emotional colors.",
        writing: "Reflect on what you might shift for better balance.",
        gratitude: "Appreciate one rhythm that supports you.",
      },
      {
        day: 14,
        spiritual: "Where are your thoughts focused lately?",
        art: "Create a thought bubble scene.",
        writing: "Write about what's taking up mental space and why.",
        gratitude: "Identify one clarity moment you received today.",
      },
    ],
  },
  {
    week: 3,
    theme: "Letting Go & Release",
    intention: "Release what no longer serves you and make space for growth.",
    quote: "Letting go is the first step toward freedom.",
    mandalaHint: "Draw flowing shapes, balloons, or leaves drifting.",
    reflectionQuestions: [
      "What did you release this week?",
      "How did letting go shift your energy?",
      "What patterns are you noticing?",
    ],
    days: [
      {
        day: 15,
        spiritual: "What are you holding onto that no longer serves you?",
        art: "Draw a balloon or leaf drifting away.",
        writing: 'Journal a release statement: "I am letting go of…"',
        gratitude: "Acknowledge one relief or lightness from letting go.",
      },
      {
        day: 16,
        spiritual: "What do you fear losing?",
        art: "Color a protective shell or barrier.",
        writing: "Reflect on how fear might be keeping you stuck.",
        gratitude: "Appreciate one courage-filled action today.",
      },
      {
        day: 17,
        spiritual: "What could you forgive yourself for?",
        art: 'Create a symbolic "forgiveness fire" or light image.',
        writing: "Write a letter offering yourself grace and release.",
        gratitude: "Acknowledge one step toward self-forgiveness.",
      },
      {
        day: 18,
        spiritual:
          "What past version of you is ready to be honored and released?",
        art: "Draw a timeline with colors or symbols.",
        writing: "Journal about what that version taught you.",
        gratitude: "Appreciate one lesson from your past self.",
      },
      {
        day: 19,
        spiritual: "What burdens have you inherited or absorbed?",
        art: "Illustrate a backpack and fill it with images of burdens.",
        writing: "Write about what you're ready to take out.",
        gratitude: "Name one lighter feeling after acknowledging it.",
      },
      {
        day: 20,
        spiritual: "What does freedom look like?",
        art: "Draw open doors, windows, wings, or rivers.",
        writing: "Journal about how it feels to let go.",
        gratitude: "Recognize one freedom moment today.",
      },
      {
        day: 21,
        spiritual: "What kind of healing are you craving right now?",
        art: 'Use soothing colors to create a "healing field."',
        writing: "Describe the healing that would nourish you most.",
        gratitude: "Appreciate one step you took toward healing today.",
      },
    ],
  },
  {
    week: 4,
    theme: "Joy & Playfulness",
    intention: "Invite lightness, laughter, and creativity into daily life.",
    quote: "Joy is not in things; it is in us.",
    mandalaHint: "Draw playful shapes, sunbursts, or bubbles.",
    reflectionQuestions: [
      "Where did you experience joy this week?",
      "How did playfulness shift your mindset?",
      "What surprised you about your creative expression?",
    ],
    days: [
      {
        day: 22,
        spiritual: "What makes your spirit feel light?",
        art: "Draw or color balloons, bubbles, or sunshine.",
        writing: "Write a joy list of 10 little things.",
        gratitude: "Recognize one moment of pure delight.",
      },
      {
        day: 23,
        spiritual: "When did you last laugh freely?",
        art: "Create a colorful doodle of laughter energy.",
        writing: "Write about a moment that brought pure laughter.",
        gratitude: "Appreciate the laughter today.",
      },
      {
        day: 24,
        spiritual: "What would your inner child love to do today?",
        art: "Draw using playful colors or crayons.",
        writing: "Journal a letter from your inner child.",
        gratitude: "Name one small, playful act you enjoyed.",
      },
      {
        day: 25,
        spiritual: "How do you define play?",
        art: "Illustrate a playground or play-based memory.",
        writing: "Reflect on how you can bring more play into your week.",
        gratitude: "Appreciate one playful opportunity.",
      },
      {
        day: 26,
        spiritual: "What song lifts your spirit?",
        art: "Create abstract art inspired by its rhythm.",
        writing: "Write about what this song unlocks in you.",
        gratitude: "Note one feeling this music inspired.",
      },
      {
        day: 27,
        spiritual: "What would you do if fear didn't stop you?",
        art: "Draw a brave version of yourself.",
        writing: "Journal what that version would say to you.",
        gratitude: "Recognize one courageous act today.",
      },
      {
        day: 28,
        spiritual: "What sparks your creativity?",
        art: 'Design a "creativity altar" with images or symbols.',
        writing: "Write about what makes you feel alive when creating.",
        gratitude: "Appreciate one source of inspiration this week.",
      },
    ],
  },
  {
    week: 5,
    theme: "Gratitude & Growth",
    intention:
      "Notice, honor, and cultivate the people, moments, and lessons that nourish you.",
    quote: "Gratitude turns what we have into enough.",
    mandalaHint: "Draw leaves, expanding circles, or blooming shapes.",
    reflectionQuestions: [
      "What grew in you this week?",
      "What surprised you about gratitude?",
      "What small blessings mattered most?",
    ],
    days: [
      {
        day: 29,
        spiritual: "What has helped you grow this year?",
        art: "Create a growing plant or tree scene.",
        writing: "Write a gratitude note to the growth.",
        gratitude: "Appreciate one way you've changed.",
      },
      {
        day: 30,
        spiritual: "Who in your life are you grateful for?",
        art: "Create a gratitude mandala with their names.",
        writing: "Journal how they've shaped you.",
        gratitude: "Name someone you're thankful for today.",
      },
      {
        day: 31,
        spiritual: "What is a hidden blessing you now recognize?",
        art: "Draw a raincloud turning into flowers.",
        writing: "Reflect on how time helped you see it.",
        gratitude: "Name a disguised blessing.",
      },
      {
        day: 32,
        spiritual: "What daily rituals bring comfort?",
        art: "Draw a tea cup, candle, or sacred space.",
        writing: "Write about your favorite simple rituals.",
        gratitude: "Appreciate a soothing routine.",
      },
      {
        day: 33,
        spiritual: "What is something you take for granted?",
        art: "Create a spotlight scene.",
        writing: "Journal appreciation for it.",
        gratitude: "Name one overlooked gift.",
      },
      {
        day: 34,
        spiritual: "What lesson did nature teach you recently?",
        art: "Illustrate the lesson with nature symbols.",
        writing: "Reflect on how nature mirrors your inner life.",
        gratitude: "Recognize one nature teaching today.",
      },
      {
        day: 35,
        spiritual: "What's one thing you're grateful for today, right now?",
        art: "Color it with care and detail.",
        writing: "Write how it impacted your day.",
        gratitude: "End with one simple gratitude.",
      },
    ],
  },
  {
    week: 6,
    theme: "Compassion & Self-Love",
    intention:
      "Soften your relationship with yourself and practice embodied kindness.",
    quote: "You yourself, as much as anyone, deserve your love and affection.",
    mandalaHint: "Draw hearts, soft shapes, clouds, or open hands.",
    reflectionQuestions: [
      "Where did you practice compassion this week?",
      "What softened in you?",
      "What part of you needs more love?",
    ],
    days: [
      {
        day: 36,
        spiritual: "What part of yourself needs love today?",
        art: "Draw a healing heart around it.",
        writing: "Write a compassionate letter to yourself.",
        gratitude: "Appreciate one strength you often overlook.",
      },
      {
        day: 37,
        spiritual: "How do you talk to yourself in hard moments?",
        art: "Illustrate your inner critic vs. inner nurturer.",
        writing: "Rewrite the script with kindness.",
        gratitude: "Recognize one gentle thought you offered today.",
      },
      {
        day: 38,
        spiritual: "What makes you worthy — just as you are?",
        art: "Color your name with symbols of worthiness.",
        writing: "Journal 5 affirmations of enough-ness.",
        gratitude: "List one thing you love about yourself.",
      },
      {
        day: 39,
        spiritual: "What boundaries do you need for self-care?",
        art: "Draw a peaceful circle or container.",
        writing: "Write about a boundary you're ready to honor.",
        gratitude: "Appreciate one boundary that protects you.",
      },
      {
        day: 40,
        spiritual: "What does self-love look like in action?",
        art: "Sketch a self-care menu.",
        writing: "Choose one action and describe how it supports you.",
        gratitude: "Celebrate a loving action you took today.",
      },
      {
        day: 41,
        spiritual: "What do you admire about yourself?",
        art: "Illustrate a mirror or frame with strengths.",
        writing: "Write a celebration of your growth.",
        gratitude: "Honor one admirable quality.",
      },
      {
        day: 42,
        spiritual: "How can you be softer with yourself today?",
        art: "Create a gentle image (clouds, water, hands).",
        writing: 'Journal a soft permission: "It\'s okay to…"',
        gratitude: "Appreciate your own gentleness.",
      },
    ],
  },
  {
    week: 7,
    theme: "Stillness & Inner Listening",
    intention: "Slow down and tune into the quieter frequencies within.",
    quote: "Only in stillness can the heart whisper its truth.",
    mandalaHint: "Draw moons, waves, breath lines, or quiet shapes.",
    reflectionQuestions: [
      "What messages arose in stillness?",
      "What part of you asked for rest?",
      "What softened when you slowed down?",
    ],
    days: [
      {
        day: 43,
        spiritual: "What is silence trying to tell you?",
        art: "Draw or color a resting moon.",
        writing: "Journal what emerges in the quiet.",
        gratitude: "Appreciate one message you received.",
      },
      {
        day: 44,
        spiritual: "What part of you needs rest?",
        art: "Illustrate a cozy nest or bed.",
        writing: "Reflect on what rest means beyond sleep.",
        gratitude: "Honor one restful moment.",
      },
      {
        day: 45,
        spiritual: "Where is your breath today?",
        art: "Draw a breath pattern or wave.",
        writing: "Describe your breath and what it reflects.",
        gratitude: "Appreciate one breath that grounded you.",
      },
      {
        day: 46,
        spiritual: "What helps you slow down?",
        art: "Draw a snail, river, or still lake.",
        writing: "Write about how slowing down shifts perspective.",
        gratitude: "Recognize one moment of slowness.",
      },
      {
        day: 47,
        spiritual: "What does your inner voice sound like?",
        art: "Color a heart-shaped ear or sound wave.",
        writing: "Write down a message it's whispering.",
        gratitude: "Appreciate one inner truth.",
      },
      {
        day: 48,
        spiritual: "How do you access wisdom within?",
        art: "Illustrate a candle or inner flame.",
        writing: "Reflect on a time your wisdom guided you.",
        gratitude: "Honor one wise choice.",
      },
      {
        day: 49,
        spiritual: "What is your spirit asking for right now?",
        art: "Draw an open hand or empty cup.",
        writing: "Journal about how you might respond.",
        gratitude: "Recognize one soulful need.",
      },
    ],
  },
  {
    week: 8,
    theme: "Authenticity & Truth",
    intention:
      "Reveal your genuine self and speak your truth gently and fully.",
    quote: "Live as though who you are is enough — because it is.",
    mandalaHint: "Draw masks, open doors, flames, or unfolding petals.",
    reflectionQuestions: [
      "What truth surfaced this week?",
      "What part of you wants to come forward?",
      "What did authenticity feel like in your body?",
    ],
    days: [
      {
        day: 50,
        spiritual: "What's something you've been hiding?",
        art: "Draw a mask, then a face underneath.",
        writing: "Journal what you wish you could say or show.",
        gratitude: "Appreciate one truth you acknowledged today.",
      },
      {
        day: 51,
        spiritual: "What truth do you want to live by?",
        art: "Create an image or symbol of your truth.",
        writing: "Write your personal manifesto.",
        gratitude: "Recognize one value guiding you today.",
      },
      {
        day: 52,
        spiritual: "Where in your life are you pretending?",
        art: "Draw contrasting sides of yourself.",
        writing: "Journal what feels real and what feels forced.",
        gratitude: "Appreciate one honest moment.",
      },
      {
        day: 53,
        spiritual: "What does your soul want to express?",
        art: "Color freely without judgment.",
        writing: "Reflect on what showed up unexpectedly.",
        gratitude: "Acknowledge one sincere expression.",
      },
      {
        day: 54,
        spiritual: "When have you felt most like you?",
        art: "Illustrate that moment or space.",
        writing: "Write about what made it feel true.",
        gratitude: "Honor one authentic moment today.",
      },
      {
        day: 55,
        spiritual: "What values guide your life?",
        art: "Draw a compass with values as directions.",
        writing: "Describe how each value shows up in your life.",
        gratitude: "Appreciate one guiding principle.",
      },
      {
        day: 56,
        spiritual: "What parts of you are ready to come forward?",
        art: "Draw a doorway or threshold.",
        writing: "Journal what lies on the other side.",
        gratitude: "Celebrate one emerging part of yourself.",
      },
    ],
  },
  {
    week: 9,
    theme: "Sacred Simplicity",
    intention: "Strip away the unnecessary and return to what truly matters.",
    quote: "Simplicity reveals the essence.",
    mandalaHint: "Draw minimal shapes, open circles, or spacious patterns.",
    reflectionQuestions: [
      "What felt simple and nourishing this week?",
      "What did you release or declutter?",
      "How did simplicity shift your spirit?",
    ],
    days: [
      {
        day: 57,
        spiritual: "What simple moment brought you peace this week?",
        art: "Draw that moment using soft, neutral tones.",
        writing: "Write about how simplicity nurtures your spirit.",
        gratitude: "Name one simple gift from today.",
      },
      {
        day: 58,
        spiritual: "What daily routine can become sacred with intention?",
        art: "Draw a simple ritual (tea, walking, stretching).",
        writing: "Journal how you can bring more presence to it.",
        gratitude: "Appreciate one quiet ritual.",
      },
      {
        day: 59,
        spiritual: "What are you overcomplicating in life?",
        art: "Draw a tangled line turning into a smooth path.",
        writing: "Reflect on what could be simplified.",
        gratitude: "Honor one choice to simplify.",
      },
      {
        day: 60,
        spiritual: 'What does a "slow day" look like to you?',
        art: "Sketch or paint your ideal slow-living day.",
        writing: "Describe how you feel when things move slowly.",
        gratitude: "Appreciate one slow moment.",
      },
      {
        day: 61,
        spiritual: "How can you make space for more ease?",
        art: "Illustrate open space or minimal shapes.",
        writing: "Write about where you can release pressure.",
        gratitude: "Recognize one moment of ease.",
      },
      {
        day: 62,
        spiritual: "What distractions pull you from what really matters?",
        art: "Draw a symbol for each distraction.",
        writing: "Journal how you might gently return to what's true.",
        gratitude: "Appreciate one moment of focus.",
      },
      {
        day: 63,
        spiritual: "What brings you quiet joy?",
        art: "Use one color to represent joy in simplicity.",
        writing: "Write about a small joy that feels like a gift.",
        gratitude: "Name one subtle joy.",
      },
    ],
  },
  {
    week: 10,
    theme: "Energy & Movement",
    intention:
      "Listen to your body and explore the flow of energy within and around you.",
    quote: "Energy flows where attention goes.",
    mandalaHint: "Draw spirals, waves, or shapes that show motion.",
    reflectionQuestions: [
      "How did your energy change this week?",
      "What movement felt nourishing?",
      "Where did your attention naturally flow?",
    ],
    days: [
      {
        day: 64,
        spiritual: "What energizes you naturally?",
        art: "Draw spirals or vibrant patterns.",
        writing: "Journal how energy flows through your day.",
        gratitude: "Appreciate one burst of energy.",
      },
      {
        day: 65,
        spiritual: "How does your body want to move today?",
        art: "Create a dance-inspired abstract shape.",
        writing: "Write a dialogue with your body's wisdom.",
        gratitude: "Celebrate one moment of movement.",
      },
      {
        day: 66,
        spiritual: "What drains your spirit?",
        art: "Illustrate a leaky bucket or withering flower.",
        writing: "Journal about one way to protect your energy.",
        gratitude: "Recognize one way you preserved energy today.",
      },
      {
        day: 67,
        spiritual: "How do you know when you're aligned?",
        art: "Draw a centered line or mandala.",
        writing: "Write about a moment you felt in perfect flow.",
        gratitude: "Appreciate one aligned moment.",
      },
      {
        day: 68,
        spiritual: "What is your body telling you right now?",
        art: "Color a body outline showing tension or calm.",
        writing: "Reflect on messages from the sensations.",
        gratitude: "Thank your body for one message.",
      },
      {
        day: 69,
        spiritual: "Where is your energy needed most?",
        art: 'Draw or color an "energy map."',
        writing: "Write about where you want to direct your energy this week.",
        gratitude: "Appreciate clarity around your focus.",
      },
      {
        day: 70,
        spiritual: "What does vitality look like for you?",
        art: "Create a radiant health or light symbol.",
        writing: "Journal one habit that supports your vitality.",
        gratitude: "Name one thing that made you feel alive today.",
      },
    ],
  },
  {
    week: 11,
    theme: "Vision & Inner Wisdom",
    intention:
      "Connect to your deepest knowing and the future you are growing toward.",
    quote: "Your vision becomes clear when you look within.",
    mandalaHint: "Draw horizons, paths, eyes, or rings.",
    reflectionQuestions: [
      "What visions surfaced this week?",
      "What wisdom repeated itself?",
      "What clarity emerged?",
    ],
    days: [
      {
        day: 71,
        spiritual: "What vision do you hold for your life?",
        art: "Draw a dream landscape or symbolic horizon.",
        writing: "Describe your vision in detail.",
        gratitude: "Appreciate that the vision is unfolding.",
      },
      {
        day: 72,
        spiritual: "What does your future self want you to know?",
        art: "Create an abstract portrait of your future self.",
        writing: "Write a letter from that version of you.",
        gratitude: "Thank your future self for guidance.",
      },
      {
        day: 73,
        spiritual: "What insights keep resurfacing lately?",
        art: "Use repeating shapes or symbols to show the message.",
        writing: "Journal how you're being invited to listen.",
        gratitude: "Recognize one repeated insight.",
      },
      {
        day: 74,
        spiritual: "What are you being called toward?",
        art: "Draw a bridge or path leading forward.",
        writing: "Describe what your soul is reaching for.",
        gratitude: "Appreciate one step toward this calling.",
      },
      {
        day: 75,
        spiritual: "What truths have you uncovered recently?",
        art: "Draw layered rings (tree rings, petals, etc.).",
        writing: "Reflect on what you now know that you didn't before.",
        gratitude: "Honor one truth.",
      },
      {
        day: 76,
        spiritual: "What do your dreams or daydreams show you?",
        art: "Illustrate an image from a dream.",
        writing: "Explore a possible message from it.",
        gratitude: "Appreciate one creative insight from dreaming.",
      },
      {
        day: 77,
        spiritual: "What wisdom lives in your body?",
        art: "Sketch a body map filled with intuitive symbols.",
        writing: "Write from the perspective of one part of your body.",
        gratitude: "Thank your body for its wisdom.",
      },
    ],
  },
  {
    week: 12,
    theme: "Connection & Wholeness",
    intention:
      "Deepen your sense of belonging — to yourself, others, and the world.",
    quote: "We become whole through connection.",
    mandalaHint: "Draw circles, interconnected lines, unity symbols.",
    reflectionQuestions: [
      "What connection felt meaningful this week?",
      "Where did you feel belonging?",
      "What helped you feel whole?",
    ],
    days: [
      {
        day: 78,
        spiritual: "Who or what reminds you that you're not alone?",
        art: "Create a connection web or circle.",
        writing: "Journal about the feeling of belonging.",
        gratitude: "Acknowledge one connection.",
      },
      {
        day: 79,
        spiritual: "How do you connect to something greater than yourself?",
        art: "Draw a symbol of spiritual connection.",
        writing:
          "Write about your relationship to the divine, nature, or the collective.",
        gratitude: "Appreciate one moment of spiritual connection.",
      },
      {
        day: 80,
        spiritual: 'What does "wholeness" feel like?',
        art: "Color a complete circle, spiral, or infinity symbol.",
        writing: "Reflect on moments you felt whole.",
        gratitude: "Name one moment of inner harmony.",
      },
      {
        day: 81,
        spiritual: "How do you show love to others?",
        art: "Illustrate a love language in action.",
        writing: "Write about how giving love has healed you.",
        gratitude: "Appreciate your capacity to love.",
      },
      {
        day: 82,
        spiritual: "What role does community play in your healing?",
        art: "Draw a group of hands, hearts, or people.",
        writing: "Reflect on the importance of support.",
        gratitude: "Name one supportive person or community.",
      },
      {
        day: 83,
        spiritual: "How can you open your heart more?",
        art: "Draw an open heart with radiant lines.",
        writing: "Write about what vulnerability means to you.",
        gratitude: "Appreciate one open-hearted moment.",
      },
      {
        day: 84,
        spiritual: "Where in your life do you feel most connected?",
        art: "Illustrate a moment or place of strong connection.",
        writing: "Journal why it's sacred to you.",
        gratitude: "Recognize one sacred connection.",
      },
    ],
  },
  {
    week: 13,
    theme: "Integration & Embodiment",
    intention: "Integrate all you've learned and embody your growth.",
    quote: "Integration transforms experience into wisdom.",
    mandalaHint: "Draw a final symbol representing your journey.",
    reflectionQuestions: [
      "What has shifted in the last 90 days?",
      "What truths stayed with you?",
      "What will you carry forward?",
    ],
    days: [
      {
        day: 85,
        spiritual: "What has shifted in you over the last 90 days?",
        art: 'Draw a "before and after" symbolic self.',
        writing: "Reflect on your transformation.",
        gratitude: "Appreciate one profound shift.",
      },
      {
        day: 86,
        spiritual: "What truth have you embodied?",
        art: "Create a visual affirmation or symbolic tattoo.",
        writing: "Journal about a lesson that is now part of you.",
        gratitude: "Honor the truth you now live.",
      },
      {
        day: 87,
        spiritual: "What creative practice do you want to keep?",
        art: 'Design a page titled "My Sacred Habit."',
        writing: "Write how this journal supported you.",
        gratitude: "Celebrate the habit you built.",
      },
      {
        day: 88,
        spiritual: "What does it mean to live in alignment?",
        art: "Illustrate aligned chakras, roots, or paths.",
        writing: "Reflect on what keeps you centered.",
        gratitude: "Appreciate one aligned action today.",
      },
      {
        day: 89,
        spiritual: "How will you continue to honor your growth?",
        art: "Draw a blooming garden or celebration image.",
        writing: "Write a commitment to yourself going forward.",
        gratitude: "Give thanks for your journey.",
      },
      {
        day: 90,
        spiritual: "What does wholeness mean to you now?",
        art: "Create a symbolic self-portrait or collage.",
        writing: "Write a final closing letter to yourself.",
        gratitude: "Honor the entire path that brought you here.",
      },
    ],
  },
];

export function getDayData(
  dayNum: number,
): { week: WeekData; day: DayData } | null {
  for (const week of WEEKS) {
    const day = week.days.find((d) => d.day === dayNum);
    if (day) return { week, day };
  }
  return null;
}

export const CHECK_IN_DAYS = [30, 60, 90];
